apiVersion: v1
kind: ReplicaSet
metadata: 
  name: replicas
  # lables belong to replicaset resource
  labels:
    app: nginx
    tier: frontend

spec:
  replicas: 3
  selector:
    matchLables:
      tier: frontend
      app: nginx

# below is the pod definition 
  template:
    metadata: 
      labels: 
        tier: frontend
        app: nginx
        project: xyz
    
    spec: 
      containers:
      - name: nginx
        image: nginx 