apiVersion: v1
kind: Pod
metadata:
  name: node-affinity

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpression: 
          - key: project
            operator: In
            values:
            - expense
  containers: 
    name: nginx
    image: nginx
  tolerations:
  - key: "project"
    # operator: "Exists"
    operator: "Equal"
    value: "expense"
    effect: "NoSchedule"
  - key: "project"
    operator: "Exists"
    effect: "NoSchedule"
