apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-soft 

spec:
  affinity:
    nodeAffinity:
      PreferredDuringSchedulingIgnoredDuringExecution:   # Here toleration is not 
      - weight: 1
        preference: 
          matchExpression: 
          - key: project
            operator: In
            values:
            - expense