apiVersion: v1
kind: Pod
metadata:
  name: pod-1 
  labels:
    labels: 
      name: pod-1
      purpose: affinity
spec:   
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2 
  labels:
    labels: 
      name: pod-2
      purpose: affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpression:
          - key: name
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone
        
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3 
  labels:
    labels: 
      name: pod-3
      purpose: affinity
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpression:
          - key: name
            operator: In
            values:
            - pod-1
        topologyKey: "kubernetes.io/hostname"
        
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always