apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static

spec:
  capacity:
    storage: 5Gi
  VolumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  PersistentVolumeClaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    VolumeHandle: # To be given by user created in efs file system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  VolumeName: efs-static
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
  labels:
    purpose: efs-static
    component: app
spec:
  containers:
    name: app
    image: nginx
  volumeMounts: 
  - name: persistant-storage
    mountPath: /usr/share/nginx/html
  volumes:
  - name: persistant-storage
    PersistentVolumeClaim:
      claimName: efs-static-claim

---
kind: Service
apiVersion: v1
metadata:
  name: efs-static
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
    component: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
