apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec: 
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    purpose: efs-dynamic
spec:
  containers:
    name: nginx
    image: nginx
    volumeMounts:
    - name: persistant-storage
      mountPath: /usr/share/nginx/html
    volumes:
    - name: persistant-storage
      PersistentVolumeClaim:
        claimName: efs-dynamic
---
apiVersion: v1
kind: LoadBalancer
metadata:
  name: efs-dynamic
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

